### Data Analysis Class
**ASSIGNMENT 1**

In [1]:
import pandas as pd

In [2]:
aids = pd.read_csv("C:/Users/kenechukwu.ifediorah/OneDrive - EverCare (1)/Documents/PythonDA/Datasets/aids.csv")

In [3]:
aids

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,0.1,...,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,0.1,...,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2756,Yemen,2020,5500,500,500,100,100,200,0.1,0.1,...,500,100,1100,1000,0.05,11000,6300,3700,1000,10000
2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,2.3,...,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,2.9,...,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

**Finding the country with highest number of HIV infected people**
For this, we have to find the maximum value in the `Data.People Living with HIV.Total` column

In [4]:
df = pd.DataFrame(aids)

In [5]:
df

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,0.1,...,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,0.1,...,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2756,Yemen,2020,5500,500,500,100,100,200,0.1,0.1,...,500,100,1100,1000,0.05,11000,6300,3700,1000,10000
2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,2.3,...,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,2.9,...,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

I'll be using the `Data.People Living with HIV.Total` column  be cause from the dtaa description, that column gives us the total number of people suffering from AIDS in this year (The latest year in the data set)

In [6]:

column = df["Data.People Living with HIV.Total"]
max_value = column.max()
column_index = column.idxmax()
print(max_value)
print(column_index)

7800000
2741

I want to check the row to confirm this

In [7]:
print(df.iloc[column_index])

Country                                                South Africa
Year                                                           2020
Data.AIDS-Related Deaths.AIDS Orphans                       1600000
Data.AIDS-Related Deaths.Adults                               79000
Data.AIDS-Related Deaths.All Ages                             83000
Data.AIDS-Related Deaths.Children                              3900
Data.AIDS-Related Deaths.Female Adults                        29000
Data.AIDS-Related Deaths.Male Adults                          49000
Data.HIV Prevalence.Adults                                     19.1
Data.HIV Prevalence.Young Men                                   3.5
Data.HIV Prevalence.Young Women                                10.4
Data.New HIV Infections.Young Adults                         200000
Data.New HIV Infections.Male Adults                           77000
Data.New HIV Infections.Female Adults                        140000
Data.New HIV Infections.Children                              12000
Data.New HIV Infections.All Ages                             230000
Data.New HIV Infections.Adults                               220000
Data.New HIV Infections.Incidence Rate Among Adults            6.42
Data.People Living with HIV.Total                           7800000
Data.People Living with HIV.Male Adults                     2700000
Data.People Living with HIV.Female Adults                   4800000
Data.People Living with HIV.Children                         310000
Data.People Living with HIV.Adults                          7500000
Name: 2741, dtype: object

Now we have ascertained the highest number in the `Data.People Living with HIV.Total` column and it's index, we can use the index to get the country from the country column

In [8]:
country = df["Country"]

In [9]:
country

0                              Afghanistan
1                                  Algeria
2                                   Angola
3                                Argentina
4                                  Armenia
                       ...
2754    Venezuela (Bolivarian Republic of)
2755                              Viet Nam
2756                                 Yemen
2757                                Zambia
2758                              Zimbabwe
Name: Country, Length: 2759, dtype: object

In [10]:
highest_country = country[column_index]

In [11]:
highest_country

'South Africa'

From this, we can tell that South Africa has the highest number of people living with AIDS.

**Now we have to find out the factor affecting that from the data**